name: CI

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  pull_request:
    branches:
      - main  # Change this to your default branch if different

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: your_database
          MYSQL_USER: your_user
          MYSQL_PASSWORD: your_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mysqlclient  # Install MySQL client for Django

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        env:
          MYSQL_HOST: db
          MYSQL_USER: your_user
          MYSQL_PASSWORD: your_password
          MYSQL_DB: your_database
        run: |
          python manage.py test
